---
- block:
  - name: Check the system
    raw: uname -a
    register: OS

  - include_tasks: ubuntu.yml
    when: '"Ubuntu" in OS.stdout or "Linux" in OS.stdout'

  - include_tasks: freebsd.yml
    when: '"FreeBSD" in OS.stdout'

  - name: Gather additional facts
    import_tasks: facts.yml

  - name: Sysctl tuning
    sysctl: name="{{ item.item }}" value="{{ item.value }}"
    with_items:
      - "{{ sysctl|default([]) }}"
    tags:
      - always

  - meta: flush_handlers
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
